[lib]
crate-type = ["rlib"]

[package]
name = "photon_dsl"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[dependencies]
regex = "1.10.6"
rustc-hash = "2.0.0"
pest = "2.7.11"
pest_derive = "2.7.11"
lazy_static = "1.5.0"
