[package]
name = "photon"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "thin"
#strip = true
debug = true
panic = "abort"
opt-level = 3
codegen-units = 1

[dependencies]
base16ct = { version = "0.2.0", features = ["alloc"] }
clap = { version = "4.5.16", features = ["derive"] }
httparse = "1.9.4"
md-5 = "0.10.6"
regex = "1.10.6"
ureq = "2.10.1"
walkdir = "2.5.0"
yaml-rust2 = "0.8.1"
