[package]
name = "photon-cli"
version = "0.2.0"
edition = "2024"
rust-version = "1.85"

[[bin]]
name = "photon"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
photon = { path = "../photon" }