[package]
name = "photon-cli"
version = "0.2.0"
edition = "2021"
rust-version = "1.75"

[[bin]]
name = "photon"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
photon = { path = "../photon" }