[package]
name = "photon-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "photon"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
photon = { path = "../photon", features = ["rustls"] }